package ru.novoscan.trkpd.domain;

import java.util.Date;

/**
 * DataSensor generated by hbm2java
 */
public class DataSensorValues {

	private long dasvId;

	private long dasvDasnId;

	private long dasvSpmdId;

	private String dasvKey;

	private Date dasvDatetime;

	private float dasvValue;

	public DataSensorValues() {
	}

	public DataSensorValues(long dasvId, long dasvSpmdId, long dasvDasnId,
			String dasvKey, float dasvValue, Date dasvDatetime) {
		this.dasvId = dasvId;
		this.dasvKey = dasvKey;
		this.dasvDasnId = dasvDasnId;
		this.dasvDatetime = dasvDatetime;
		this.dasvValue = dasvValue;
		this.dasvSpmdId = dasvSpmdId;
	}

	public DataSensorValues(long dasvId, long dasvSpmdId, String dasvKey,
			float dasvValue, Date dasvDatetime) {
		this.dasvId = dasvId;
		this.dasvKey = dasvKey;
		this.dasvDatetime = dasvDatetime;
		this.dasvValue = dasvValue;
		this.dasvSpmdId = dasvSpmdId;
	}

	public long getDasvId() {
		return this.dasvId;
	}

	public void setDasvId(long dasvId) {
		this.dasvId = dasvId;
	}

	public long getDasvDasnId() {
		return dasvDasnId;
	}

	public void setDasvDasnId(long dasvDasnId) {
		this.dasvDasnId = dasvDasnId;
	}

	public Date getDasvDatetime() {
		return dasvDatetime;
	}

	public void setDasvDatetime(Date dasvDatetime) {
		this.dasvDatetime = dasvDatetime;
	}

	public float getDasvValue() {
		return dasvValue;
	}

	public void setDasvValue(float dasvValue) {
		this.dasvValue = dasvValue;
	}

	public String getDasvKey() {
		return dasvKey;
	}

	public void setDasvKey(String dasvKey) {
		this.dasvKey = dasvKey;
	}

	public long getDasvSpmdId() {
		return dasvSpmdId;
	}

	public void setDasvSpmdId(long dasvSpmdId) {
		this.dasvSpmdId = dasvSpmdId;
	}

	public boolean isValid() {
		if ((this.dasvDasnId != 0L) && (this.dasvKey != null)
				&& (this.dasvDatetime != null)) {
			return true;
		}
		return false;
	}

	public void clear() {

		dasvId = 0L;

		dasvDasnId = 0L;

		dasvSpmdId = 0L;

		dasvKey = null;

		dasvDatetime = null;

		dasvValue = 0;
	}
}
