#!/bin/sh
#
# trkprd_tfm        Startup script for the TRKPRD for Universal Driver
#
# chkconfig: - 88 10
# description: Startup script for the TRKPRD for Teltonika Driver. \
# processname: ru.novoscan.UDPtrkprd
# config: /opt/novoscan/trkprd/trkprd_tfm.conf
# pidfile: /var/run/trkprd_tfm.pid

# Source function library.
. /etc/rc.d/init.d/functions

#set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="TRKPRD for Teltonika Daemon"
NAME="trkprd"
USER="novoscan"
HOME="/opt/novoscan/${NAME}"
CP="$HOME/trkprd-1.0.0.jar:/opt/novoscan/lib/postgresql.jar:/opt/novoscan/lib/log4j.jar:/opt/novoscan/lib/commons-lang3.jar"
MAIN="ru.novoscan.trkpd.Track"
ARGS="-f /opt/novoscan/trkprd/trkprd_tfm.conf"
RETVAL=0

DAEMON="/usr/bin/java -server -cp $CP -Djava.awt.headless=true -Dlog4j.configuration=file://${HOME}/log4j_tfm.properties $MAIN $ARGS"
PIDFILE="/var/run/${NAME}_tfm.pid"
SCRIPTNAME="/etc/init.d/${NAME}_tfm"

# Gracefully exit if the package has been removed.
test -x /usr/bin/java || exit 0

# ---------------------------------------
# Function that starts the daemon/service
# ---------------------------------------
start()
{
	echo -n "Starting $DESC $NAME_tfm: "
	PID=`pgrep -f "$DAEMON"`
	if [ -n "$PID" ]; then
		echo_warning
		echo $PID > $PIDFILE
               	RETVAL=0
	else
		su -p -s /bin/sh $USER -c "${DAEMON} &>/dev/null &"
		PID=`pgrep -f "${DAEMON}"`
		if [ -n "${PID}" ]; then
			echo_success
	               	RETVAL=0
		else
			echo_failure
	               	RETVAL=1
		fi
	fi
	echo
	return ${RETVAL}
}
 
# --------------------------------------
# Function that stops the daemon/service
# --------------------------------------
stop()
{
  	echo -n "Stopping $DESC ${NAME}_tfm: "
	PID=`pgrep -f "$DAEMON"`
        if [ $UID -ne 0 ]; then
                RETVAL=1
		echo_failure
		echo
        else
		if [ -n "$PID" ]; then
			pkill -f "$DAEMON"
			RETVAL=$?
			if [ $RETVAL -eq 0 ]; then
				echo_success
			else
				echo_failure
                		RETVAL=1
			fi
		else
			echo_failure
                	RETVAL=1
		fi
        fi
	echo
        return $RETVAL
}

case "$1" in
start)
  start
;;
stop)
  stop
;;
restart|force-reload)
  stop
  sleep 1
  start
;;
status)
        PID=`pgrep -f "$DAEMON"`
        if [ -n "$PID" ]; then
                RETVAL=0
                echo "$DESC is running: $PID"
        else
                RETVAL=1
                echo "$DESC is stopped"
        fi
;;
*)
echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|status}" >&2
exit 1
;;
esac

exit $RETVAL

